services:
  nextipdatabase:
    image: mysql:latest
    container_name: nextip
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: onejob
    ports:
      - '3306:3306'
  onejobserver:
    image: workoutserver:1.0
    container_name: nextipserver
    build:
      context: ./
    ports:
        - '8080:80'
    volumes:
      - ./app:/var/www/laravel_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - nextipdatabase